#pragma once

enum AlifMemAllocatorName {
	ALIFMEM_ALLOCATOR_NOT_SET = 0,
	ALIFMEM_ALLOCATOR_DEFAULT = 1,
	ALIFMEM_ALLOCATOR_DEBUG = 2,
	ALIFMEM_ALLOCATOR_MALLOC = 3,
	ALIFMEM_ALLOCATOR_MALLOC_DEBUG = 4,
#ifdef WITH_ALIFMALLOC
	PYMEM_ALLOCATOR_PYMALLOC = 5,
	PYMEM_ALLOCATOR_PYMALLOC_DEBUG = 6,
#endif
};
