#pragma once

static inline void _alifUStr_initStaticStrings(AlifInterpreter* interp) {
	AlifObject* string{};

	string = &ALIF_ID(CANCELLED);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(AlifRepr);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(__abstractMethods__);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(__annotate__);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(__bases__);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(__buildClass__);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(__builtins__);
	_alifUStr_internStatic(interp, &string);
	//string = &ALIF_ID(__call__);
	//_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(__class__);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(__classCell__);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(__classDict__);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(__classDictCell__);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(__classGetItem__);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(__complex__);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(__dict__);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(__dictOffset__);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(__doc__);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(__eq__);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(__file__);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(__firstLineno__);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(__format__);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(__getAttr__);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(__hash__);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(__initSubclass__);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(__lengthHint__);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(__loader__);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(__module__);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(__mroEntries__);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(__name__);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(__new__);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(__notes__);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(__origClass__);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(__path__);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(__package__);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(__prepare__);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(__qualname__);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(__setName__);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(__slots__);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(__spec__);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(__staticAttributes__);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(__subClassCheck__);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(__typeParams__);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(__weakListOffset__);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(__weakRef__);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(_findAndLoad);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(_initializing);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(_isTextEncoding);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(_WindowsConsoleIO);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(Builtins);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(Encoding);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(End);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(Errors);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(File);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(Fileno);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(Flush);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(HasLocation);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(Join);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(keys);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(ListComp);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(MetaClass);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(Mro);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(NFields);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(NSequenceFields);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(Origin);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(Path);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(ReadInto);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(Sep);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(Stderr);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(Stdin);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(Stdout);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(TextIOWrapper);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(Top);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_ID(Write);
	_alifUStr_internStatic(interp, &string);

	string = &ALIF_STR(AnonListComp);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_STR(AnonModule);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_STR(DblPercent);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_STR(Defaults);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_STR(DotLocals);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_STR(Empty);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_STR(Format);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_STR(GenericBase);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_STR(IsAtty);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_STR(KWDefaults);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_STR(TypeParams);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_STR(True);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_STR(False);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_STR(Mode);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_STR(Name);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_STR(Obj);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_STR(Open);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_STR(Raw);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_STR(__call__);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_STR(__init__);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_STR(__import__);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_STR(__repr__);
	_alifUStr_internStatic(interp, &string);
	string = &ALIF_STR(_io);
	_alifUStr_internStatic(interp, &string);
}
